import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DOWNLOADS = ROOT / "downloads"
TEXT = ROOT / "extracted_text"
RETRIEVAL_DATE = "2026-06-03"


def p(*parts):
    return str((ROOT / Path(*parts)).resolve())


def d(name):
    return str((DOWNLOADS / name).resolve())


def t(name):
    return str((TEXT / name).resolve())


source_rows = [
    {
        "id": "media-root",
        "source_scope": "Vestrum website evidence",
        "title": "Vestrum Health media/publications page",
        "year": "2026 retrieval",
        "source_type": "Website HTML",
        "vestrum_url": "https://www.vestrumhealth.com/media.php",
        "current_access_url": "https://www.vestrumhealth.com/media.php",
        "local_files": p("vestrum_media_page.html") + "; " + p("vestrum_dme_media_items.json"),
        "access_status": "Saved HTML and parsed DME-tagged media cards.",
        "retrieval_date": RETRIEVAL_DATE,
        "notes": "Authoritative Vestrum website evidence for the core publication set.",
    },
    {
        "id": "core-01",
        "source_scope": "Core Vestrum website qualifying publication",
        "title": "Increasing Incidence and Prevalence of Common Retinal Diseases in Retina Practices Across the United States",
        "year": "2021",
        "source_type": "Journal article landing page/abstract",
        "vestrum_url": "https://www.healio.com/ophthalmology/journals/osli/2021-1-52-1/%7B65045259-a9c1-4583-8dd8-a5214905e298%7D/increasing-incidence-and-prevalence-of-common-retinal-diseases-in-retina-practices-across-the-united-states",
        "current_access_url": "https://scholars.mssm.edu/en/publications/increasing-incidence-and-prevalence-of-common-retinal-diseases-in",
        "local_files": d("01_MountSinai_Rosenblatt_Incidence_Prevalence_Common_Retinal_Diseases_2021.html") + "; " + t("01_MountSinai_Rosenblatt_Incidence_Prevalence_Common_Retinal_Diseases_2021.txt") + "; " + d("01_UniversityMiami_Rosenblatt_Incidence_Prevalence_Common_Retinal_Diseases_2021.html"),
        "access_status": "Healio blocked scripted access with HTTP 403. Saved an institutional abstract/methods page. The University of Miami page is an Esploro shell and not substantively useful.",
        "retrieval_date": RETRIEVAL_DATE,
        "notes": "Broad retinal disease incidence/prevalence analysis; includes DME but is not DME-only.",
    },
    {
        "id": "core-02",
        "source_scope": "Core Vestrum website qualifying publication",
        "title": "Evaluation of Patients Receiving Intravitreal Antivascular Endothelial Growth Factor for Diabetic Macular Edema in Clinical Practice in the United States",
        "year": "2020/2021",
        "source_type": "Journal article PDF",
        "vestrum_url": "https://www.vestrumhealth.com/vestrum-health-documents/PitcherD-VESTRUM-DME-JVRD-September-30-2020.pdf",
        "current_access_url": "https://3333112.fs1.hubspotusercontent-na1.net/hubfs/3333112/PitcherD-VESTRUM-DME-JVRD-September-30-2020Evaluation%20of%20Patients%20Receiving%20Intravitreal.pdf",
        "local_files": d("02_Pitcher_Evaluation_Intravitreal_AntiVEGF_DME_JVRD_2020.pdf") + "; " + t("02_Pitcher_Evaluation_Intravitreal_AntiVEGF_DME_JVRD_2020.txt"),
        "access_status": "Old Vestrum PDF URL now redirects to a CoreVitas/PPD page. Valid PDF saved from HubSpot mirror.",
        "retrieval_date": RETRIEVAL_DATE,
        "notes": "DME anti-VEGF treatment-intensity and VA outcomes analysis.",
    },
    {
        "id": "nonqual-03",
        "source_scope": "Vestrum website DME-tagged, excluded",
        "title": "Ophthalmology Retina Enters Year 4: Some Comments on Neovascular Age-Related Macular Degeneration and Diabetic Macular Edema",
        "year": "2020",
        "source_type": "Editorial/commentary",
        "vestrum_url": "https://www.vestrumhealth.com/vestrum-health-documents/SomeCommentsonNeovascularAgeRelatedMacularDegenerationandDiabeticMacularEdemaAndrewPSchachatMD.pdf",
        "current_access_url": "",
        "local_files": "",
        "access_status": "Excluded from methods extraction because it is a DME-tagged commentary/editorial rather than a Vestrum database analysis of DME patients.",
        "retrieval_date": RETRIEVAL_DATE,
        "notes": "Logged so every DME-tagged Vestrum website item is accounted for.",
    },
    {
        "id": "core-04",
        "source_scope": "Core Vestrum website qualifying publication",
        "title": "Visual Acuity Outcomes and Anti-VEGF Therapy Intensity in Diabetic Macular Edema: A Real-World Analysis of 28,658 Patient Eyes",
        "year": "2020/2021",
        "source_type": "Journal article full text HTML",
        "vestrum_url": "https://www.vestrumhealth.com/vestrum-health-documents/VisualAcuityOutcomesandAntiVascularEndothelialGrowthFactorTherapyIntensityinNeovascularAgeRelatedMacularDegenerationPatients.pdf",
        "current_access_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7848066/",
        "local_files": d("04_PMC7848066_Visual_Acuity_DME_fulltext.html") + "; " + t("04_PMC7848066_Visual_Acuity_DME_fulltext.txt") + "; " + d("04_PMC7848066_Visual_Acuity_DME.pdf_or_html") + "; " + d("04_ScholarWorks_item_page.html"),
        "access_status": "Old Vestrum link now redirects and has a misleading nAMD filename. PMC full text saved. PMC PDF endpoint returned proof-of-work HTML. ScholarWorks item page saved, but its downloadable bitstream appeared unrelated and was not retained.",
        "retrieval_date": RETRIEVAL_DATE,
        "notes": "Vestrum card says 26,658 eyes; published article says 28,658 patient eyes.",
    },
    {
        "id": "core-05",
        "source_scope": "Core Vestrum website qualifying publication",
        "title": "Real-world Outcomes of Anti-Vascular Endothelial Growth Factor Therapy in Diabetic Macular Edema in the United States",
        "year": "2018",
        "source_type": "Journal article PDF plus PubMed page",
        "vestrum_url": "https://www.vestrumhealth.com/vestrum-health-documents/RealworldOutcomesofAntiVascularEndothelialGrowthFactorTherapyinDiabeticMacularEdemaintheUnitedStates.pdf",
        "current_access_url": "https://3333112.fs1.hubspotusercontent-na1.net/hubfs/3333112/RealworldOutcomesofAntiVascularEndothelialGrowthFactorTherapyinDiabeticMacularEdemaintheUnitedStates.pdf",
        "local_files": d("05_Ciulla_Bracha_Pollack_Williams_Realworld_AntiVEGF_DME_2018.pdf") + "; " + t("05_Ciulla_Bracha_Pollack_Williams_Realworld_AntiVEGF_DME_2018.txt") + "; " + d("05_PubMed_Ciulla_Bracha_Pollack_Williams_Realworld_DME_2018.html") + "; " + t("05_PubMed_Ciulla_Bracha_Pollack_Williams_Realworld_DME_2018.txt"),
        "access_status": "Old Vestrum PDF URL now redirects to a CoreVitas/PPD page. Valid PDF saved from HubSpot mirror. Vestrum labels it editorial, but the paper is a primary retrospective analysis.",
        "retrieval_date": RETRIEVAL_DATE,
        "notes": "Treatment-naive DME anti-VEGF outcomes by starting agent and baseline VA.",
    },
    {
        "id": "context-06",
        "source_scope": "Broader relevant Vestrum-DME context",
        "title": "Evolving Treatment Patterns in Diabetic Macular Edema Between 2015 and 2020",
        "year": "2023",
        "source_type": "Journal article PDF",
        "vestrum_url": "Not listed on retrieved Vestrum DME media cards",
        "current_access_url": "https://www.asrs.org/content/documents/evolving-treatment-patterns-in-diabetic-macular-edema-between-2015-and-2020.pdf",
        "local_files": d("06_Sodhi_Evolving_Treatment_Patterns_DME_2015_2020_ASRS.pdf") + "; " + t("06_Sodhi_Evolving_Treatment_Patterns_DME_2015_2020_ASRS.txt"),
        "access_status": "Valid PDF saved.",
        "retrieval_date": RETRIEVAL_DATE,
        "notes": "Context source for diagnosis-indexed treatment-pattern methods.",
    },
    {
        "id": "context-07",
        "source_scope": "Broader relevant Vestrum-DME context",
        "title": "Longer-Term Anti-VEGF Outcomes in Neovascular AMD, Diabetic Macular Edema, and Vein Occlusion-Related Macular Edema",
        "year": "2022",
        "source_type": "Journal article PDF",
        "vestrum_url": "Not listed on retrieved Vestrum DME media cards",
        "current_access_url": "Open-access institutional/Elsevier source identified during search",
        "local_files": d("07_Ciulla_Longer_Term_AntiVEGF_Outcomes_DME_nAMD_RVO_2022.pdf") + "; " + t("07_Ciulla_Longer_Term_AntiVEGF_Outcomes_DME_nAMD_RVO_2022.txt"),
        "access_status": "Valid PDF saved.",
        "retrieval_date": RETRIEVAL_DATE,
        "notes": "Context source for longer-term DME VA outcomes.",
    },
    {
        "id": "context-08",
        "source_scope": "Broader relevant Vestrum-DME context",
        "title": "Bevacizumab-First Treatment Protocol AC Versus Real-World Treatment for Diabetic Macular Edema: Cost Analysis",
        "year": "2024",
        "source_type": "Journal article PDF",
        "vestrum_url": "Not listed on retrieved Vestrum DME media cards",
        "current_access_url": "https://www.asrs.org/content/documents/bevacizumab-first-treatment-protocol-ac-versus-real-world-treatment-for-diabetic-macular-edema-cost-analysis.pdf",
        "local_files": d("08_Grewal_Bevacizumab_First_Protocol_AC_vs_Real_World_DME_Cost_2024.pdf") + "; " + t("08_Grewal_Bevacizumab_First_Protocol_AC_vs_Real_World_DME_Cost_2024.txt"),
        "access_status": "Valid PDF saved.",
        "retrieval_date": RETRIEVAL_DATE,
        "notes": "Context source for cost and utilization methods.",
    },
    {
        "id": "context-09",
        "source_scope": "Broader relevant Vestrum-DME context",
        "title": "Cost-Effectiveness of Step Therapy in Diabetic Macular Edema: Protocol AC and Real-World Data",
        "year": "2025",
        "source_type": "Journal article PDF",
        "vestrum_url": "Not listed on retrieved Vestrum DME media cards",
        "current_access_url": "https://www.asrs.org/content/documents/cost-effectiveness-of-step-therapy-in-diabetic-macular-edema-protocol-ac-and-real-world-data.pdf",
        "local_files": d("09_Leung_Cost_Effectiveness_DME_Step_Therapy_2025.pdf") + "; " + t("09_Leung_Cost_Effectiveness_DME_Step_Therapy_2025.txt"),
        "access_status": "Valid PDF saved.",
        "retrieval_date": RETRIEVAL_DATE,
        "notes": "Context source for cost-effectiveness modeling methods.",
    },
    {
        "id": "context-10",
        "source_scope": "Broader relevant Vestrum-DME context",
        "title": "Visual Outcomes and Dosing Frequencies of Patients with Diabetic Macular Edema Treated with Faricimab Versus Other Anti-VEGF Agents",
        "year": "2026",
        "source_type": "PubMed abstract/landing page",
        "vestrum_url": "Not listed on retrieved Vestrum DME media cards",
        "current_access_url": "https://pubmed.ncbi.nlm.nih.gov/40616668/",
        "local_files": d("10_PubMed_Macha_Faricimab_vs_Other_AntiVEGF_DME_2026.html") + "; " + t("10_PubMed_Macha_Faricimab_vs_Other_AntiVEGF_DME_2026.txt"),
        "access_status": "PubMed page saved. SAGE full text/PDF returned HTTP 403. PMC full text is embargoed until 2027-04-09.",
        "retrieval_date": RETRIEVAL_DATE,
        "notes": "Context source for newer-agent and durability endpoints; abstract-level methods only.",
    },
]


methods_rows = [
    {
        "id": "core-01",
        "source_scope": "Core Vestrum website qualifying publication",
        "access_status": "Abstract/methods landing page saved; Healio blocked full article download",
        "title": "Increasing Incidence and Prevalence of Common Retinal Diseases in Retina Practices Across the United States",
        "year": "2021",
        "publication_type": "Journal article",
        "evidence_basis": "Institutional abstract/methods page",
        "local_evidence_files": t("01_MountSinai_Rosenblatt_Incidence_Prevalence_Common_Retinal_Diseases_2021.txt"),
        "database_or_data_source": "Vestrum Health Database",
        "design": "Retrospective study",
        "study_period": "January 2014 to December 2019",
        "practice_or_database_size": "58 retina practices; 3,086,791 eyes examined",
        "dme_definition": "Eyes with DME identified among eyes with common retinal diseases; exact diagnostic-code/clinical definition not available in saved abstract-level source",
        "treatment_naive_definition": "Not applicable; epidemiology/incidence-prevalence study",
        "sample_screened_or_assessed": "3,086,791 eyes examined",
        "sample_included": "DME: 270,703 eyes",
        "index_date": "Not extracted from accessible abstract-level source",
        "follow_up_window": "Disease incidence/prevalence assessed over 2014-2019",
        "key_inclusion_exclusion": "Included eyes with wet AMD, dry AMD, DME, diabetic retinopathy without DME, BRVO, and CRVO identified in the database during the study period",
        "confounding_exclusions": "Not extracted from accessible abstract-level source",
        "unit_of_analysis": "Eye",
        "bilateral_eye_handling": "Not extracted from accessible abstract-level source",
        "treatment_or_exposure_groups": "Disease categories, including DME",
        "treatment_intensity_definition": "Not applicable",
        "baseline_va_strata": "Not central to accessible extracted methods",
        "va_method": "Not central to accessible extracted methods",
        "outcome_domains": "Incidence and prevalence of common retinal diseases; DME as one disease category",
        "statistical_methods": "Incidence/prevalence estimation; detailed statistical methods not available from saved abstract-level source",
        "key_results_for_method_context": "DME represented 8.8% of examined eyes, supporting feasibility of large-scale DME ascertainment in Vestrum.",
        "attrition_selection": "Not extracted from accessible abstract-level source",
        "limitations_or_caveats": "Broad disease epidemiology paper, not a DME-only outcomes study; full Healio article was not downloaded due HTTP 403.",
        "methods_relevance": "Useful for cohort-size feasibility and epidemiologic endpoint design; less useful for anti-VEGF outcomes design.",
    },
    {
        "id": "core-02",
        "source_scope": "Core Vestrum website qualifying publication",
        "access_status": "Full PDF saved from HubSpot mirror; original Vestrum PDF redirects",
        "title": "Evaluation of Patients Receiving Intravitreal Anti-VEGF for Diabetic Macular Edema in Clinical Practice in the United States",
        "year": "2020/2021",
        "publication_type": "Journal article",
        "evidence_basis": "Full manuscript PDF text extraction",
        "local_evidence_files": t("02_Pitcher_Evaluation_Intravitreal_AntiVEGF_DME_JVRD_2020.txt"),
        "database_or_data_source": "Vestrum Health treatment and outcomes database; deidentified EMRs queried by SQL",
        "design": "Retrospective analysis of deidentified EMRs",
        "study_period": "Index first anti-VEGF injection from 2012-01-01 to 2015-04-30; observation through 2017-04-30",
        "practice_or_database_size": "251 retina specialists at 54 private US clinics; records include demographics, procedures, diagnoses, medications, and outcomes including VA",
        "dme_definition": "Eyes newly diagnosed with DME in the Vestrum database and administered a first anti-VEGF injection",
        "treatment_naive_definition": "No prior anti-VEGF treatment recorded before first anti-VEGF injection in the study window; outside-practice prior treatment cannot be fully ruled out from extracted text",
        "sample_screened_or_assessed": "155,240 DME eyes assessed; 13,016 with first anti-VEGF treatment and VA on index",
        "sample_included": "Year-1 cohort 3,028 eyes; year-2 cohort 1,292 eyes",
        "index_date": "First anti-VEGF injection",
        "follow_up_window": "12 and 24 months after index injection; month-12 VA closest to 12 months in months 11-12; required VA at index, month 12, and at least once each quarter",
        "key_inclusion_exclusion": "Included newly diagnosed DME eyes receiving first anti-VEGF injection and accepted VA methods. Excluded treatment break greater than 11 months in 24 months after index and eyes not meeting VA/follow-up requirements; required same VA methodology per patient.",
        "confounding_exclusions": "Focused on newly diagnosed DME and anti-VEGF treated eyes; extracted text does not show detailed exclusion of other retinal diagnoses comparable to later papers",
        "unit_of_analysis": "Eye",
        "bilateral_eye_handling": "Not clearly extracted",
        "treatment_or_exposure_groups": "Injection intensity groups: <=6 versus >6 injections per year; year-2 maintained or reduced frequency subgroups",
        "treatment_intensity_definition": "<=6 versus >6 anti-VEGF injections per year",
        "baseline_va_strata": "Not the main stratification",
        "va_method": "Converted to ETDRS letters with ETDRS = 85 - (50 * logMAR)",
        "outcome_domains": "VA change and anti-VEGF injection frequency/intensity over 1 and 2 years",
        "statistical_methods": "Descriptive statistics; paired t-tests within cohorts; independent t-tests assuming unequal variance between cohorts; p < 0.05; Excel",
        "key_results_for_method_context": "Higher injection intensity in year 1 produced greater VA gain (+8.0 letters with >6 injections vs +3.7 with <=6). Reducing frequency after high year-1 dosing was associated with greater year-2 loss.",
        "attrition_selection": "Strict VA/follow-up requirements reduced 13,016 potentially eligible index-treatment eyes to 3,028 year-1 eyes and 1,292 year-2 eyes.",
        "limitations_or_caveats": "Strict follow-up/VA requirements select for more observed patients; retrospective EMR design and treatment-selection confounding.",
        "methods_relevance": "Strong template for treatment-intensity analyses with index injection, prespecified VA windows, quarterly VA, and injection-frequency cohorts.",
    },
    {
        "id": "core-04",
        "source_scope": "Core Vestrum website qualifying publication",
        "access_status": "PMC full text HTML saved; PMC PDF endpoint returned proof-of-work HTML; original Vestrum link redirects",
        "title": "Visual Acuity Outcomes and Anti-VEGF Therapy Intensity in Diabetic Macular Edema: A Real-World Analysis of 28,658 Patient Eyes",
        "year": "2020/2021",
        "publication_type": "Journal article",
        "evidence_basis": "PMC full text HTML extraction",
        "local_evidence_files": t("04_PMC7848066_Visual_Acuity_DME_fulltext.txt"),
        "database_or_data_source": "Vestrum Health Retina Database",
        "design": "Retrospective analysis",
        "study_period": "Anti-VEGF injections between January 2013 and July 2018",
        "practice_or_database_size": "Nearly 1.5 million unique patients, more than 11 million encounters, 350 US retina specialists; weekly refresh; geographically/demographically diverse panel",
        "dme_definition": "Treatment-naive DME/DMO patient eyes receiving anti-VEGF and meeting follow-up criteria",
        "treatment_naive_definition": "Treatment-naive in Vestrum during study window; prior outside-practice treatment is a general real-world data caveat",
        "sample_screened_or_assessed": "Not stated in the same way as Pitcher; final analytic cohort reported",
        "sample_included": "28,658 patient eyes",
        "index_date": "Initial anti-VEGF treatment in the study period",
        "follow_up_window": "One year; required follow-up in months 11-12",
        "key_inclusion_exclusion": "Included treatment-naive DME/DMO eyes receiving anti-VEGF and 1-year follow-up. Excluded other retinal diagnoses. Did not require three initial loading injections, unlike the 2018 study.",
        "confounding_exclusions": "Excluded other retinal diagnoses; switcher sensitivity analysis; medication comparisons remain nonrandom",
        "unit_of_analysis": "Patient eye",
        "bilateral_eye_handling": "Sensitivity analysis excluded bilateral cases",
        "treatment_or_exposure_groups": "Initial anti-VEGF agent; injection frequency; baseline VA strata; switcher sensitivity analysis; calendar year/medication trends",
        "treatment_intensity_definition": "Injection count/frequency during year 1; histogram from 1-13 injections with 32 eyes >13 excluded from subgroup display",
        "baseline_va_strata": "Yes; baseline VA strata used because ceiling effects were expected and observed",
        "va_method": "Snellen VA converted to approximate ETDRS letters using 85 + 50 * log(Snellen fraction), citing Gregori et al.",
        "outcome_domains": "Mean 1-year VA change; injection frequency; VA change by medication, baseline VA, and treatment intensity",
        "statistical_methods": "Baseline characteristics; mean change with 95% CI and nominal paired t-test p values; sensitivity excluding bilateral eyes and switchers; frequency histograms",
        "key_results_for_method_context": "Mean 6.4 injections, median 6; overall +4.2 letters; <=5 injections generally below 3-letter gain; baseline VA produced strong ceiling/floor effects.",
        "attrition_selection": "Required 1-year follow-up in months 11-12, selecting for observed patients; bilateral and switcher sensitivity analyses address part of the selection/confounding structure.",
        "limitations_or_caveats": "Retrospective EMR data; real-world VA measurement variability; medication comparisons confounded by nonrandom treatment selection; Vestrum card eye count differs from published paper.",
        "methods_relevance": "Best broad template for one-year DME anti-VEGF outcomes: large cohort, clear anti-VEGF index, baseline VA stratification, frequency analysis, and bilateral sensitivity.",
    },
    {
        "id": "core-05",
        "source_scope": "Core Vestrum website qualifying publication",
        "access_status": "Full PDF saved from HubSpot mirror; original Vestrum PDF redirects",
        "title": "Real-world Outcomes of Anti-VEGF Therapy in Diabetic Macular Edema in the United States",
        "year": "2018",
        "publication_type": "Journal article",
        "evidence_basis": "Full manuscript PDF text extraction",
        "local_evidence_files": t("05_Ciulla_Bracha_Pollack_Williams_Realworld_AntiVEGF_DME_2018.txt"),
        "database_or_data_source": "Vestrum Health Retina Database",
        "design": "Retrospective, uncontrolled review",
        "study_period": "Treatment-naive DME diagnosis/treatment from January 2011 to March 2017; follow-up available before March 2018",
        "practice_or_database_size": "More than 240 private-practice retina physicians; urban/suburban/rural 65/32/3%; regional distribution reported; more than 800,000 unique patients and more than 4.5 million encounters",
        "dme_definition": "Treatment-naive DME patients treated with anti-VEGF and meeting initial injection/follow-up criteria",
        "treatment_naive_definition": "Treatment-naive in the Vestrum record; outside-practice prior treatment is a general real-world data caveat",
        "sample_screened_or_assessed": "13,974 patients / 15,608 eyes",
        "sample_included": "6-month cohort 4,613 eyes; 12-month cohort 5,840 eyes; 24-month cohort 5,155 eyes",
        "index_date": "DME diagnosis and initial anti-VEGF treatment period",
        "follow_up_window": "Mutually exclusive 6-, 12-, and 24-month cohorts based on available follow-up/loss to follow-up",
        "key_inclusion_exclusion": "Treatment-naive DME; at least three monthly anti-VEGF injections in first 4 months; grouped by initial agent.",
        "confounding_exclusions": "Initial anti-VEGF monotherapy/agent grouping; extracted text captures corticosteroid, laser, and PRP utilization but the cohort is selected by loading injections",
        "unit_of_analysis": "Patient eye",
        "bilateral_eye_handling": "Bilateral eyes treated independently",
        "treatment_or_exposure_groups": "Initial agent: aflibercept, bevacizumab, ranibizumab; baseline VA strata",
        "treatment_intensity_definition": "At least three monthly anti-VEGF injections in first 4 months; total treatments counted by follow-up cohort",
        "baseline_va_strata": "20/201 or worse; 20/71-20/200; 20/41-20/70; 20/40 or better",
        "va_method": "VA reported as ETDRS letters/letter change; conversion details less explicit than later BJO paper",
        "outcome_domains": "VA outcomes and number of anti-VEGF treatments; corticosteroid, macular laser, and panretinal photocoagulation utilization captured",
        "statistical_methods": "Descriptive statistics; mean baseline/final VA and injections; mean change with 95% CI and nominal paired t-test p values; stratified by baseline VA",
        "key_results_for_method_context": "12-month gains were similar by initial agent: aflibercept +5.5, bevacizumab +5.5, ranibizumab +4.0 letters, with about 7.5-7.9 injections. Worse baseline VA gained more; good baseline VA lost letters.",
        "attrition_selection": "Mutually exclusive follow-up cohorts and initial loading-injection requirement select for treated/followed eyes.",
        "limitations_or_caveats": "Initial loading-injection requirement reduces generalizability; retrospective and uncontrolled; bilateral-eye independence caveat.",
        "methods_relevance": "Useful for agent-comparison framing and baseline VA strata; later 28,658-eye paper is broader because it removes the loading-injection requirement.",
    },
    {
        "id": "context-06",
        "source_scope": "Broader relevant Vestrum-DME context",
        "access_status": "Full PDF saved",
        "title": "Evolving Treatment Patterns in Diabetic Macular Edema Between 2015 and 2020",
        "year": "2023",
        "publication_type": "Journal article",
        "evidence_basis": "Full manuscript PDF text extraction",
        "local_evidence_files": t("06_Sodhi_Evolving_Treatment_Patterns_DME_2015_2020_ASRS.txt"),
        "database_or_data_source": "Vestrum Health Retina Database",
        "design": "Retrospective review",
        "study_period": "January 2015 to October 2021; annual treatment pattern analysis 2015-2020",
        "practice_or_database_size": "Aggregated longitudinal deidentified EMRs from a geographically/demographically diverse US retina specialist panel",
        "dme_definition": "Newly diagnosed DME eyes",
        "treatment_naive_definition": "Newly diagnosed DME during the study period; not a pure anti-VEGF treatment-naive outcomes cohort because untreated and non-anti-VEGF treatments are included",
        "sample_screened_or_assessed": "306,700 eyes assessed",
        "sample_included": "122,899 eyes included after criteria; 5-year follow-up subset 12,918 eyes",
        "index_date": "New DME diagnosis",
        "follow_up_window": "At least 1 year for main included cohort; 5-year subset required at least 5 years follow-up from 2015-2021",
        "key_inclusion_exclusion": "Excluded eyes with less than 1 year follow-up and pathology other than DME that might have been treated with intravitreal or macular focal laser therapy, including AMD, RVO, and myopic CNV",
        "confounding_exclusions": "Excluded competing retinal pathologies that could receive similar treatments",
        "unit_of_analysis": "Eye",
        "bilateral_eye_handling": "Bilateral eyes independent",
        "treatment_or_exposure_groups": "Untreated, anti-VEGF monotherapy, steroid monotherapy, focal laser monotherapy, and combination treatment patterns by year and cumulatively",
        "treatment_intensity_definition": "Treatment class and cumulative treatment counts over annual and 5-year windows",
        "baseline_va_strata": "Not central to treatment-pattern extraction",
        "va_method": "Snellen VA reported/extracted; VA change compared from baseline",
        "outcome_domains": "Treatment distribution, anti-VEGF/steroid/laser utilization, untreated proportion, baseline and follow-up VA change",
        "statistical_methods": "Descriptive treatment-pattern comparisons with reported p values; exact test details should be checked in full text before formal citation",
        "key_results_for_method_context": "Untreated share declined from 32.7% in 2015 to 27.7% in 2020; anti-VEGF monotherapy increased from 43.5% to 61.8%; focal laser monotherapy decreased from 9.7% to 3.0%.",
        "attrition_selection": "Required at least 1 year follow-up; 5-year subset is smaller and likely selected for continued observation.",
        "limitations_or_caveats": "Off Vestrum media page; treatment selection and loss-to-follow-up limitations; long-term cohorts can be highly selected.",
        "methods_relevance": "Useful for diagnosis-indexed treatment-pattern studies and untreated/combo therapy endpoints.",
    },
    {
        "id": "context-07",
        "source_scope": "Broader relevant Vestrum-DME context",
        "access_status": "Full PDF saved",
        "title": "Longer-Term Anti-VEGF Outcomes in Neovascular AMD, Diabetic Macular Edema, and Vein Occlusion-Related Macular Edema",
        "year": "2022",
        "publication_type": "Journal article",
        "evidence_basis": "Full manuscript PDF text extraction",
        "local_evidence_files": t("07_Ciulla_Longer_Term_AntiVEGF_Outcomes_DME_nAMD_RVO_2022.txt"),
        "database_or_data_source": "Vestrum Health Retina Database",
        "design": "Retrospective analysis",
        "study_period": "Treatment-naive patients receiving anti-VEGF between 2014 and 2019",
        "practice_or_database_size": "Approximately 1.5 million unique patients, more than 11 million encounters, 350 retina specialists; weekly refresh",
        "dme_definition": "Treatment-naive DME eyes among nAMD, DME, BRVO-ME, and CRVO-ME cohorts",
        "treatment_naive_definition": "Treatment-naive anti-VEGF eyes in the Vestrum record",
        "sample_screened_or_assessed": "Not extracted as a single screened count",
        "sample_included": "DME eyes: 40,832 at 1 year, 7,728 at 3 years, 1,192 at 5 years",
        "index_date": "Initial anti-VEGF treatment",
        "follow_up_window": "At least 12 months; distinct yearly cohorts; up to 5 years for DME/nAMD and up to 3 years for RVO",
        "key_inclusion_exclusion": "Included treatment-naive anti-VEGF-treated disease cohorts; excluded other retinal diagnoses",
        "confounding_exclusions": "Excluded other retinal diagnoses",
        "unit_of_analysis": "Patient eye",
        "bilateral_eye_handling": "Not the central extracted field",
        "treatment_or_exposure_groups": "Injection frequency strata; baseline VA strata; disease cohorts; not stratified by anti-VEGF agent due prior findings",
        "treatment_intensity_definition": "Injection count/frequency over each yearly follow-up horizon",
        "baseline_va_strata": "Yes",
        "va_method": "Snellen converted to approximate ETDRS letters using 85 + 50 * log(Snellen fraction)",
        "outcome_domains": "VA change over longer-term follow-up and injection frequency",
        "statistical_methods": "Descriptive statistics; mean VA change with 95% CI and nominal paired t-test p values; injection-frequency histograms",
        "key_results_for_method_context": "DME mean injections and VA change: 1 year 6.2 injections/+4.7 letters, 3 years 15.4/+3.3, 5 years 26.0/+3.1.",
        "attrition_selection": "Longer follow-up cohorts shrink substantially and are selected for continued observation.",
        "limitations_or_caveats": "Off Vestrum media page; DME is one of multiple disorders; longer follow-up cohorts are selected survivors.",
        "methods_relevance": "Best context for multi-year DME anti-VEGF outcome windows and durability of real-world gains.",
    },
    {
        "id": "context-08",
        "source_scope": "Broader relevant Vestrum-DME context",
        "access_status": "Full PDF saved",
        "title": "Bevacizumab-First Treatment Protocol AC Versus Real-World Treatment for Diabetic Macular Edema: Cost Analysis",
        "year": "2024",
        "publication_type": "Journal article",
        "evidence_basis": "Full manuscript PDF text extraction",
        "local_evidence_files": t("08_Grewal_Bevacizumab_First_Protocol_AC_vs_Real_World_DME_Cost_2024.txt"),
        "database_or_data_source": "Vestrum real-world DME cohort plus DRCR Protocol AC model inputs and CMS/Medicare costs",
        "design": "Cost analysis comparing modeled Protocol AC bevacizumab-first strategy versus Vestrum real-world utilization",
        "study_period": "Vestrum treatment-naive DME eyes initiating anti-VEGF in 2016 with 2-year follow-up; broader stated window 2016-2018",
        "practice_or_database_size": "Real-world Vestrum utilization data for visits, imaging, injections, and medication mix",
        "dme_definition": "Treatment-naive DME eyes with baseline VA matched to Protocol AC and anti-VEGF monotherapy",
        "treatment_naive_definition": "Treatment-naive anti-VEGF eyes in Vestrum matched to Protocol AC baseline VA range",
        "sample_screened_or_assessed": "1,556 eyes initiated anti-VEGF in 2016 for DME with 20/50-20/320 baseline VA",
        "sample_included": "1,062 eyes included after excluding steroid/laser combination care; VA-gain matched subset 346",
        "index_date": "Anti-VEGF initiation in 2016",
        "follow_up_window": "2 years",
        "key_inclusion_exclusion": "Included baseline VA 20/50-20/320 and anti-VEGF monotherapy; excluded eyes receiving steroids and/or laser in addition to anti-VEGF during 2-year follow-up",
        "confounding_exclusions": "Steroid and laser combination treatment excluded to match anti-VEGF monotherapy cost comparison",
        "unit_of_analysis": "Eye",
        "bilateral_eye_handling": "Not central to extracted cost model",
        "treatment_or_exposure_groups": "Protocol AC modeled bevacizumab-first with switch to aflibercept versus real-world Vestrum regimen; VA-gain matched sensitivity subset",
        "treatment_intensity_definition": "Injection, visit, OCT, and fundus utilization over 2 years",
        "baseline_va_strata": "Matched to Protocol AC baseline VA range rather than broad strata",
        "va_method": "VA gain used for cohort matching and comparison; full VA-conversion detail not central to extraction",
        "outcome_domains": "Costs, visits, imaging, injection counts, drug mix, VA gain",
        "statistical_methods": "Cost modeling using CMS 2022 nonfacility fee schedule and Dec 2022 Medicare Part B ASP; one-way sensitivity analyses removing modifier 25 and fundus costs",
        "key_results_for_method_context": "Real-world Vestrum care cost about 40% less than Protocol AC model with similar VA gain; real-world had 8.6 injections over 13.8 visits versus Protocol AC 16.1 injections over 22.5 visits.",
        "attrition_selection": "494 of 1,556 candidate eyes excluded because they received steroids and/or laser in addition to anti-VEGF.",
        "limitations_or_caveats": "Modeling assumptions and reimbursement inputs matter; anti-VEGF monotherapy selection may not generalize to all DME care.",
        "methods_relevance": "Template for using Vestrum as utilization/cost input rather than only VA outcome database.",
    },
    {
        "id": "context-09",
        "source_scope": "Broader relevant Vestrum-DME context",
        "access_status": "Full PDF saved",
        "title": "Cost-Effectiveness of Step Therapy in Diabetic Macular Edema: Protocol AC and Real-World Data",
        "year": "2025",
        "publication_type": "Journal article",
        "evidence_basis": "Full manuscript PDF text extraction",
        "local_evidence_files": t("09_Leung_Cost_Effectiveness_DME_Step_Therapy_2025.txt"),
        "database_or_data_source": "Vestrum real-world regimen/utilization plus Markov model and cost-effectiveness inputs",
        "design": "Theoretical Markov cost-effectiveness model from a US societal perspective",
        "study_period": "2-year modeled follow-up and 17-year lifetime horizon; Vestrum real-world data used as comparator inputs",
        "practice_or_database_size": "Not a primary cohort-size paper; uses Vestrum real-world comparator regimen from prior analysis",
        "dme_definition": "DME population modeled from Protocol AC and Vestrum real-world data",
        "treatment_naive_definition": "Inherited from underlying Protocol AC and real-world comparator sources",
        "sample_screened_or_assessed": "Model-based; no new screened Vestrum count extracted",
        "sample_included": "Model-based; no new patient-level Vestrum cohort count extracted",
        "index_date": "Treatment initiation in modeled scenarios",
        "follow_up_window": "2 years and lifetime 17-year horizon",
        "key_inclusion_exclusion": "Model scenarios and sensitivity analyses; follows Second Panel on Cost-Effectiveness and CHEERS framework",
        "confounding_exclusions": "Handled through scenario assumptions rather than patient-level exclusions",
        "unit_of_analysis": "Modeled patient/eye pathway",
        "bilateral_eye_handling": "Not applicable to extracted model summary",
        "treatment_or_exposure_groups": "Protocol AC bevacizumab-first step therapy versus Vestrum real-world regimen; reference, low-cost, and high-cost scenarios",
        "treatment_intensity_definition": "Protocol AC and real-world injection/visit patterns modeled over 2 years and lifetime scenarios",
        "baseline_va_strata": "Not central to extracted model summary",
        "va_method": "VA outcomes translated into utility/QALY differences using a VA-to-utility approach described in the paper",
        "outcome_domains": "Costs, QALYs, incremental cost-utility ratio, probability of cost-effectiveness, healthcare and societal cost categories",
        "statistical_methods": "Markov modeling, 3% annual discounting, scenario analyses, probabilistic sensitivity analysis",
        "key_results_for_method_context": "Protocol AC was more expensive at 2 years ($69,850 vs $61,304) and was not cost-effective in most probabilistic scenarios.",
        "attrition_selection": "Not applicable to model extraction; depends on underlying real-world comparator.",
        "limitations_or_caveats": "Economic model rather than standalone Vestrum patient-level outcomes study; assumptions about long-term VA and costs drive findings.",
        "methods_relevance": "Shows how Vestrum DME outcomes/utilization can support HEOR endpoints and sensitivity analyses.",
    },
    {
        "id": "context-10",
        "source_scope": "Broader relevant Vestrum-DME context",
        "access_status": "PubMed abstract only; SAGE blocked; PMC embargoed until 2027-04-09",
        "title": "Visual Outcomes and Dosing Frequencies of Patients with Diabetic Macular Edema Treated with Faricimab Versus Other Anti-VEGF Agents",
        "year": "2026",
        "publication_type": "Journal article; abstract-level extraction only",
        "evidence_basis": "PubMed abstract/landing page",
        "local_evidence_files": t("10_PubMed_Macha_Faricimab_vs_Other_AntiVEGF_DME_2026.txt"),
        "database_or_data_source": "Vestrum Health database deidentified EMRs",
        "design": "Retrospective database analysis based on abstract",
        "study_period": "January 2021 to December 2023",
        "practice_or_database_size": "Not reported in accessible abstract",
        "dme_definition": "DME eyes treated with faricimab, bevacizumab, ranibizumab, or aflibercept; treatment-naive and treatment-experienced switch cohorts",
        "treatment_naive_definition": "Treatment-naive cohort identified in abstract; detailed criteria unavailable from saved abstract",
        "sample_screened_or_assessed": "Not reported in accessible abstract",
        "sample_included": "14,103 treatment-naive eyes by injection 6; treatment-experienced faricimab switch cohort 1,378 eyes",
        "index_date": "Anti-VEGF treatment/injection series start; switch to faricimab for treatment-experienced cohort",
        "follow_up_window": "Through 6 injections in treatment-naive eyes and 2 injections in treatment-experienced eyes",
        "key_inclusion_exclusion": "Abstract identifies treatment-naive and treatment-experienced DME eyes receiving named agents; detailed criteria not available from saved abstract",
        "confounding_exclusions": "Baseline VA stratification reported; detailed exclusion criteria unavailable from abstract",
        "unit_of_analysis": "Eye",
        "bilateral_eye_handling": "Not reported in accessible abstract",
        "treatment_or_exposure_groups": "Faricimab, bevacizumab, ranibizumab, aflibercept; treatment-naive and treatment-experienced cohorts; baseline VA stratification",
        "treatment_intensity_definition": "Mean days between injections and durability through injection sequence; >=50 days between injections 5 and 6",
        "baseline_va_strata": "Yes, according to abstract",
        "va_method": "VA change reported; detailed conversion method unavailable from abstract",
        "outcome_domains": "Mean VA change and mean days between injections/dosing frequency",
        "statistical_methods": "Abstract-level comparisons; detailed methods unavailable from accessible source",
        "key_results_for_method_context": "After baseline VA stratification, faricimab outcomes were similar to other agents; faricimab more often achieved at least 50 days between injections 5 and 6 than bevacizumab or ranibizumab.",
        "attrition_selection": "Not reported in accessible abstract.",
        "limitations_or_caveats": "Full text/PDF inaccessible due publisher 403 and PMC embargo until 2027-04-09; methods extraction is abstract-level only.",
        "methods_relevance": "Useful as current evidence that Vestrum can evaluate newer agents and durability intervals, but insufficient for detailed design extraction without full text.",
    },
]


def write_csv(path, rows):
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def write_report():
    core = [row for row in methods_rows if row["source_scope"].startswith("Core")]
    context = [row for row in methods_rows if row["source_scope"].startswith("Broader")]
    report = [
        "# Vestrum Health DME Publication Methods Comparison",
        "",
        f"Retrieval date: {RETRIEVAL_DATE}",
        "",
        "## Scope and Inclusion",
        "",
        "The saved Vestrum Health media page contains five DME-tagged entries. Four are qualifying Vestrum database analyses that evaluate DME or DME-containing retinal-disease cohorts. One DME-tagged item, the Schachat 2020 Ophthalmology Retina year-4 commentary, was logged but excluded because it is not a primary Vestrum database analysis of DME patients.",
        "",
        "The core Vestrum website set is the main answer to the request. I also saved and extracted several newer Vestrum-DME publications found outside the retrieved Vestrum media page because they add useful methods context for treatment patterns, longer-term outcomes, economics, and newer anti-VEGF agents.",
        "",
        "## Deliverables in This Folder",
        "",
        "- `source_log.json` and `source_log.csv`: authoritative source URLs, local files, access status, retrieval date, and caveats.",
        "- `download_manifest.json`: corrected manifest generated from the same source log.",
        "- `methods_extraction.csv`: publication-level methods/outcomes extraction.",
        "- `downloads/`: saved PDFs, HTML landing pages, and access-evidence files.",
        "- `extracted_text/`: text extracted from saved manuscripts, abstracts, or webpages where available.",
        "- `vestrum_dme_media_items.json`: parsed DME-tagged Vestrum media cards.",
        "- `vestrum_media_page.html`: saved Vestrum media-page HTML.",
        "",
        "## Access Caveats",
        "",
        "Several original Vestrum document URLs now redirect away from the original PDFs to a CoreVitas/PPD page, so the final saved PDFs for the Pitcher 2020/2021 and Ciulla 2018 papers came from HubSpot mirrors. The Vestrum card for the 2020/2021 visual-acuity paper has a filename suggesting neovascular AMD and lists 26,658 eyes, but the published BJO article and PMC full text state DME/DMO and 28,658 patient eyes.",
        "",
        "Healio blocked scripted access to the 2021 incidence/prevalence article, so I saved an institutional abstract/methods page instead. The PMC PDF endpoint for the BJO paper returned proof-of-work HTML, so I saved the PMC full text HTML and kept the PDF-endpoint response as access evidence. A ScholarWorks item page for the BJO paper was saved, but its downloadable bitstream appeared unrelated and was not retained. SAGE blocked the 2026 faricimab full text/PDF, so that extraction is based on PubMed only.",
        "",
        "`methods_windows_raw.txt` is retained as a raw scratch extraction only. Do not use it as a final source because it contains a known unrelated manuscript block from an earlier bad ScholarWorks bitstream attempt.",
        "",
        "## Core Vestrum Website Publications",
        "",
        "| ID | Publication | Design and Cohort | Key Methods | Outcomes Studied |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in core:
        report.append(
            f"| {row['id']} | {row['title']} ({row['year']}) | {row['design']}; {row['dme_definition']}; {row['sample_included']} | Study period: {row['study_period']}. Index/follow-up: {row['index_date']}; {row['follow_up_window']}. Unit: {row['unit_of_analysis']}. | {row['outcome_domains']} |"
        )
    report.extend([
        "",
        "## Broader Relevant Vestrum-DME Publications Saved for Context",
        "",
        "| ID | Publication | Why It Matters | Methods Signal |",
        "| --- | --- | --- | --- |",
    ])
    for row in context:
        report.append(
            f"| {row['id']} | {row['title']} ({row['year']}) | {row['methods_relevance']} | {row['design']}; {row['dme_definition']}; {row['outcome_domains']} |"
        )
    report.extend([
        "",
        "## Cross-Study Methods Patterns",
        "",
        "The most common analytic frame is a retrospective patient-eye-level study of deidentified Vestrum EMR data. The treatment-outcomes papers generally define a DME eye, identify an index treatment date, require baseline VA and follow-up VA in a fixed window, then stratify by treatment intensity, baseline VA, and sometimes initial agent.",
        "",
        "The strongest one-year anti-VEGF outcome template is the 28,658-eye BJO analysis. It avoids the stricter loading-dose requirement from the 2018 paper, requires 1-year follow-up in months 11-12, excludes other retinal diagnoses, uses patient-eye analysis with bilateral-eye sensitivity, converts Snellen VA to approximate ETDRS letters, and stratifies by baseline VA and injection frequency. The Pitcher paper is better when the research question is specifically treatment intensity over 1-2 years because it requires quarterly VA and compares <=6 versus >6 injections per year.",
        "",
        "Baseline VA stratification is essential. Across the anti-VEGF outcome papers, better baseline VA produces ceiling effects and sometimes letter loss, while worse baseline VA produces larger gains. Injection frequency is also central: lower real-world injection intensity is repeatedly associated with smaller VA gains than trial protocols.",
        "",
        "For treatment-pattern questions, the diagnosis-indexed Sodhi approach is more appropriate than treatment-indexed anti-VEGF outcome cohorts because it captures untreated eyes, focal laser, steroid use, anti-VEGF monotherapy, and combinations. For economics, Grewal and Leung show how Vestrum can supply real-world visits, imaging, injections, agent mix, and VA outcomes for cost or cost-effectiveness models.",
        "",
        "## Outcomes Previously Studied",
        "",
        "- Epidemiology: incidence and prevalence of DME among other retinal diseases.",
        "- Treatment utilization: anti-VEGF, focal laser, steroids, combinations, untreated eyes, visits, OCT/fundus imaging, and agent mix.",
        "- Visual outcomes: VA change at 6, 12, and 24 months; longer-term 3- and 5-year VA outcomes; VA by baseline VA strata.",
        "- Treatment intensity/durability: number of injections, <=6 versus >6 injections, injection-frequency histograms, days between injections, and treatment-intensity trajectories.",
        "- Agent comparisons: aflibercept, bevacizumab, ranibizumab, and faricimab, with switcher and treatment-experienced analyses where available.",
        "- Economic outcomes: modeled cost, cost-effectiveness, QALYs, utilization-based costs, and sensitivity/probabilistic analyses.",
        "",
        "## Recommended Future Vestrum DME Study Template",
        "",
        "1. Define the research question first: epidemiology, treatment patterns, anti-VEGF outcomes, durability, agent comparison, or economic utilization. Use diagnosis-indexed cohorts for treatment-pattern questions and treatment-indexed cohorts for anti-VEGF outcome questions.",
        "2. Identify treatment-naive or newly diagnosed DME eyes, and exclude other retinal diagnoses likely to confound treatment or outcome attribution, especially AMD, RVO, and myopic CNV when the endpoint is DME-specific anti-VEGF response.",
        "3. Use eye as the primary unit of analysis, but prespecify how bilateral eyes will be handled. A sensitivity analysis excluding bilateral cases is a defensible minimum.",
        "4. For anti-VEGF outcomes, set the index date as the first anti-VEGF injection. Require baseline VA and a fixed follow-up window such as months 11-12 for one-year outcomes. Add quarterly VA requirements only when the question depends on treatment-intensity trajectory.",
        "5. Convert Snellen VA to approximate ETDRS letters using a documented formula, and report limitations from non-protocolized real-world VA testing.",
        "6. Prespecify baseline VA strata because ceiling effects are consistent and can dominate crude mean VA change.",
        "7. Stratify by injection frequency/treatment intensity. A practical minimum is injection count over 12 months; richer analyses can use frequency bins, <=6 versus >6 injections, or days between injections.",
        "8. For agent comparisons, report switcher sensitivity analyses and avoid causal wording unless methods adjust for treatment-selection bias.",
        "9. Use descriptive statistics and mean change with 95% CI for core outcome summaries. Paired t-tests are common in prior papers, but modern comparative studies should consider multivariable or propensity methods if causal agent comparisons are intended.",
        "10. For HEOR work, capture visits, imaging, injections, medication mix, and VA change directly from Vestrum, then document cost sources and run one-way plus probabilistic sensitivity analyses.",
        "",
        "## Key Methodological Caveats",
        "",
        "All Vestrum DME studies reviewed here are retrospective or model-based uses of retrospective real-world data. The main risks are nonrandom treatment selection, variable VA collection methods, possible treatment outside contributing practices, loss-to-follow-up selection, bilateral-eye dependence, inconsistent anatomic/OCT abstraction, and cohort definitions that can select for more adherent or more actively treated patients.",
        "",
        "## File Map",
        "",
        "- Source log JSON: `source_log.json`",
        "- Source log CSV: `source_log.csv`",
        "- Corrected download manifest: `download_manifest.json`",
        "- Methods extraction CSV: `methods_extraction.csv`",
        "- Raw Vestrum media HTML: `vestrum_media_page.html`",
        "- Parsed media cards: `vestrum_dme_media_items.json`",
    ])
    (ROOT / "vestrum_dme_methods_comparison.md").write_text("\n".join(report) + "\n", encoding="utf-8")


def main():
    (ROOT / "source_log.json").write_text(json.dumps(source_rows, indent=2), encoding="utf-8")
    (ROOT / "download_manifest.json").write_text(json.dumps(source_rows, indent=2), encoding="utf-8")
    write_csv(ROOT / "source_log.csv", source_rows)
    write_csv(ROOT / "methods_extraction.csv", methods_rows)
    write_report()
    print(json.dumps({
        "source_rows": len(source_rows),
        "methods_rows": len(methods_rows),
        "created": [
            p("source_log.json"),
            p("source_log.csv"),
            p("download_manifest.json"),
            p("methods_extraction.csv"),
            p("vestrum_dme_methods_comparison.md"),
        ],
    }, indent=2))


if __name__ == "__main__":
    main()
